"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = ["Black.png", "BlackWithQ.png", "GenericMatrixOperations.py",
              "GUI.py", "Solutions.py", "White.png", "WhiteWithQ.png"]
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
